### ISSUE TITLE
Using store.metaForType() has been deprecated

### ISSUE THREAD

**Issue by riklaunim** [escalant3/ember-data-tastypie-adapter#52]
In Ember Data 1.0.0-beta.14 using store.metaForType got deprected.

https://github.com/emberjs/data/blob/master/CHANGELOG.md

**Comment by pedrokiefer** [comment]
@riklaunim thanks for reporting this. I'll take a look into it.

**Comment by riklaunim** [comment]
Looks like it's just a one line search-and-replace.

**Comment by pedrokiefer** [comment]
@riklaunim sorry for the delay, I've pushed a new version on beta.14 branch.

If everybody agrees I can merge it to master.
