### ISSUE TITLE
Adapter lookup

### ISSUE THREAD

**Issue by dbollinger** [escalant3/ember-data-tastypie-adapter#57]
I believe the parameter passed into `adapterFor` here should be relationship.type rather than typeKey:

    relationshipToResourceUri: function (relationship, value){
            if (!value)
              return value;

            var store = relationship.type.store,
                typeKey = relationship.type.typeKey;
    
            return store.adapterFor(typeKey).buildURL(typeKey, get(value, 'id'));
          },

ember-data looks for type.typeKey in the adapterFor function:

      /**
        Returns the adapter for a given type.

        @method adapterFor
        @private
        @param {subclass of DS.Model} type
        @return DS.Adapter
      */
      adapterFor: function(type) {
        var container = this.container, adapter;

        if (container) {
          adapter = container.lookup('adapter:' + type.typeKey) || container.lookup('adapter:application');
        }

        return adapter || get(this, 'defaultAdapter');
      },

**Comment by pedrokiefer** [comment]
The adapter is currently somewhat broken with ember-data beta.15 and beta.16, I'll try to fix it.

**Comment by dbollinger** [comment]
Looks like your latest updates for beta.17 compatibility have taken care of this issue.  Everything seems to be working very nicely- nice work on the ember-cli support.

**Comment by pedrokiefer** [comment]
Great, I still need to update the docs, but things should be working.
